version: '3.8'

services:
  integration-suspect-service:
    build: .
    container_name: integration-suspect-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - integration_network

networks:
  integration_network:
    external: true